apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
    service: webserver
  name: giropops
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    args: 
    - sleep
    - "1800"
    resources:
      limits:
        cpu: "500m"
        memory: "128Mi"
      requests:
        cpu: "250m"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
