apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus-1
    service: webserver
  name: girus-1
spec:
  containers:
  - image: nginx
    name: girus-1
    resources: {}
  - image: busybox
    name: busybox
    args: 
    - sleep
    - "600"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
