apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: my-pvc
  name: my-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: giropops
  selector:
    matchLabels:
      storage: lento