apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pod-monitor
  labels:
    app: pod-monitor
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: pod-monitor
  podMetricsEndpoints:
  - interval: 10s
    path: /metrics
    targetPort: 9113