apiVersion: v1
kind: Pod
metadata:
  name: pod-monitor
  labels:
    app: pod-monitor
spec:
  containers:
  - name: pod-monitor
    image: prom/pod-monitor:1.0.0
    ports:
    - containerPort: 80
      name: http
    - containerPort: 9113
      name: metrics
    volumeMounts:
    - name: pod-monitor-config
      mountPath: /etc/pod-monitor/config.yaml
      subPath: config.yaml
    args:
      - '-pod-monitor.scrape-uri=http://localhost/metrics'
    resources:
      requests:
        cpu: 0.3
        memory: 128Mi
  volumes: 
  - name: pod-monitor-config
    configMap:
      name: pod-monitor-config
      defaultMode: 420
