apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
          name: http
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
    - name: nginx-exporter
      image: 'nginx/nginx-prometheus-exporter:0.11.0'
      args:
        - '-nginx.scrape-uri=http://localhost/metrics'
      resources:
        limits:
          memory: 128Mi
          cpu: 0.3
      ports:
        - containerPort: 9113
          name: metrics
  volumes:
    - name: nginx-config
      configMap:
        defaultMode: 420
        name: nginx-config