apiVersion: v1
kind: Service
metadata:
  name: locust
  labels:
    app: locust
spec:
  type: NodePort
  ports:
  - port: 8089
    targetPort: 8089
    nodePort: 30089  # Porta para acessar o Locust UI
    protocol: TCP
    name: web-ui
  - port: 5557
    targetPort: 5557
    protocol: TCP
    name: master
  selector:
    app: locust
