apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-https
  labels:
    app: nginx-https
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-https
  template:
    metadata:
      labels:
        app: nginx-https
    spec:
      containers:
      - name: nginx-https
        image: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-tls
          mountPath: /etc/nginx/tls
          readOnly: true
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      - name: nginx-tls
        secret:
          secretName: cert-tls
          items:
          - key: tls.crt
            path: certificado.crt
          - key: tls.key
            path: chave-privada.key
