apiVersion: v1
kind: Pod 
metadata:
  name: pod-secret
spec:
  containers:
  - name: container-secret
    image: nginx
    env:
    - name: SECRET_USERNAME # nome da variável que vai receber o valor do secret
      valueFrom:
        secretKeyRef: 
          name: primeiro-secrets # nome do secret que vai ser usado
          key: username
    - name: SECRET_PASSWORD # nome da variável que vai receber o valor do secret
      valueFrom:
        secretKeyRef:
          name: primeiro-secrets # nome do secret que vai ser usado
          key: password # nome da chave que vai ser usada