apiVersion: v1
kind: Pod 
metadata:
  name: pod-secret
spec:
  containers:
  - name: container-secret
    image: nginx
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: primeiro-secrets
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: primeiro-secrets
          key: password