apiVersion: v1 
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None  # Note the lowercase 'c' and the correct indentation
  selector:
    app: nginx