apiVersion: v1
kind: Service
metadata:
  name: giropops-service
  labels:
    app: giropops-service
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None  # Não é um serviço headless, não tem IP clusterizado, não tem IP interno.
  selector:
    app: giropops-set
