apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: giropops-set
spec:
  serviceName: "giropops-set" # Nome do serviço que será criado para o StatefulSet
  replicas: 3
  selector:
    matchLabels:
      app: giropops-set
  template:
    metadata:
      labels:
        app: giropops-set
    spec:
      containers:
      - name: giropops-set
        image: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-persistent-storage
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: nginx-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"] # Significa que o volume será usado por um único node
      resources:
        requests:
          storage: 1Gi
